In [1]:
import numpy as np

In [11]:
np.allclose(28.999993, 29)

True

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
idxes = np.array([1, 2])
idxes.sort()

print(arr)

other = np.array([[0, 0], [0, 0]])

arr[np.ix_(idxes, idxes)] = other
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 0, 0],
       [7, 0, 0]])

In [ ]:
c = np.array([2, 3 , 4, 5, 6])
c = c.transpose()

idx = 2

arr[idx]

test = np.array([[0, 0], [0, 0]])



In [ ]:
matrix[idxes, :][:, jdxes]

In [6]:
arr[np.ix_(idxes, idxes)] = test

In [ ]:
np

array([[1, 2, 3],
       [4, 0, 0],
       [7, 0, 0]])

In [8]:
lol = np.array([1], dtype=np.int64)
lol = lol[lol != 1]
lol

array([], dtype=int64)