In [23]:
import numpy as np

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
idxes = np.array([1, 2])
idxes.sort()

print(arr)

ar = arr[:, idxes][idxes, :]
ar

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5, 6],
       [8, 9]])

In [ ]:
c = np.array([2, 3 , 4, 5, 6])
c = c.transpose()

idx = 2

arr[idx]

array([7, 8, 9])